# Feature Engineering
---

## 0. Constants

In [74]:
EDA_DATA_PATH = "../data/processed/eda_data.pkl"
PRICE_DATA = "../data/raw/price_data.csv"
FE_DATA_EXPORT_PATH = "../data/processed/fe_data.pkl"

---
## 1. Imports

In [76]:
import pandas as pd
import pickle

from sklearn.preprocessing import OneHotEncoder

In [26]:
eda_df = pd.read_pickle(EDA_DATA_PATH)
eda_df.head()

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,price_off_peak_fix_diff,price_peak_fix_diff,price_mid_peak_fix_diff,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565969,24.339581,16.226389,1
1,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565969,24.339581,16.226389,1
2,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565973,24.339578,16.226383,1
3,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565973,24.339578,16.226383,1
4,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565973,24.339578,16.226383,1

In [27]:
date_cols = ["date_activ", "date_end", "date_modif_prod", "date_renewal"]
for col in date_cols:
    eda_df[col] = pd.to_datetime(eda_df[col], format="%Y-%m-%d")

eda_df.head()

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,price_off_peak_fix_diff,price_peak_fix_diff,price_mid_peak_fix_diff,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565969,24.339581,16.226389,1
1,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565969,24.339581,16.226389,1
2,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565973,24.339578,16.226383,1
3,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565973,24.339578,16.226383,1
4,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,3.700961,24.43733,16.291555,0.125976,0.103395,0.071536,40.565973,24.339578,16.226383,1

In [28]:
price_df = pd.read_csv(PRICE_DATA)
price_df["price_date"] = pd.to_datetime(price_df["price_date"], format='%Y-%m-%d')
price_df.head()

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0

---
## 2. Feature Engineering

In [39]:
#Create Year columns out of date columns
eda_df['year_modif_prod'] = eda_df['date_modif_prod'].dt.year
eda_df['year_renewal'] = eda_df['date_renewal'].dt.year

In [40]:
#Create 
monthly_price_by_id = price_df.groupby(['id', 'price_date']).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()
monthly_price_by_id.head()

,id,price_date,price_off_peak_var,price_off_peak_fix
0,0002203ffbb812588b632b9e628cc38d,2015-01-01,0.126098,40.565969
1,0002203ffbb812588b632b9e628cc38d,2015-02-01,0.126098,40.565969
2,0002203ffbb812588b632b9e628cc38d,2015-03-01,0.128067,40.728885
3,0002203ffbb812588b632b9e628cc38d,2015-04-01,0.128067,40.728885
4,0002203ffbb812588b632b9e628cc38d,2015-05-01,0.128067,40.728885

In [43]:
#Get January & December prices
jan_prices = monthly_price_by_id.groupby('id').first().reset_index()
dec_prices = monthly_price_by_id.groupby('id').last().reset_index()

#Change columns names
jan_prices.rename(columns={'price_off_peak_var': 'jan_1', 'price_off_peak_fix': 'jan_2'}, inplace=True)
dec_prices.rename(columns={'price_off_peak_var': 'dec_1', 'price_off_peak_fix': 'dec_2'}, inplace=True)

In [47]:
#Create January-December difference dataframe
diff = pd.DataFrame()
diff["id"] = jan_prices["id"]
diff["offpeak_diff_dec_january_energy"] = dec_prices['dec_1'] - jan_prices['jan_1']
diff["offpeak_diff_dec_january_power"] = dec_prices['dec_2'] - jan_prices['jan_2']
diff.head()

,id,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,0002203ffbb812588b632b9e628cc38d,-0.006192,0.162916
1,0004351ebdd665e6ee664792efc4fd13,-0.004104,0.177779
2,0010bcc39e42b3c2131ed2ce55246e3c,0.050443,1.500000
3,0010ee3855fdea87602a5b7aba8e42de,-0.010018,0.162916
4,00114d74e963e47177db89bc70108537,-0.003994,-0.000001

In [48]:
eda_df = eda_df.merge(diff, on='id', how='left')
eda_df.head(3)

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix,churn,year_modif_prod,year_renewal,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,0.103395,0.071536,40.565969,24.339581,16.226389,1,2015,2015,0.020057,3.700961
1,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,0.103395,0.071536,40.565969,24.339581,16.226389,1,2015,2015,0.020057,3.700961
2,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.0,...,0.103395,0.071536,40.565973,24.339578,16.226383,1,2015,2015,0.020057,3.700961

### Drop unnecessary columns

In [49]:
eda_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175149 entries, 0 to 175148
Data columns (total 55 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   id                               175149 non-null  object
 1   channel_sales                    175149 non-null  object
 2   cons_12m                         175149 non-null  int64
 3   cons_gas_12m                     175149 non-null  int64
 4   cons_last_month                  175149 non-null  int64
 5   date_activ                       175149 non-null  datetime64[ns]
 6   date_end                         175149 non-null  datetime64[ns]
 7   date_modif_prod                  175149 non-null  datetime64[ns]
 8   date_renewal                     175149 non-null  datetime64[ns]
 9   forecast_cons_12m                175149 non-null  float64
 10  forecast_cons_year               175149 non-null  int64
 11  forecast_discount_energy         175149 non-null  float64
 12  forecast_meter_rent_12m          175149 non-null  float64
 13  forecast_price_energy_off_peak   175149 non-null  float64
 14  forecast_price_energy_peak       175149 non-null  float64
 15  forecast_price_pow_off_peak      175149 non-null  float64
 16  has_gas                          175149 non-null  object
 17  imp_cons                         175149 non-null  float64
 18  margin_gross_pow_ele             175149 non-null  float64
 19  margin_net_pow_ele               175149 non-null  float64
 20  nb_prod_act                      175149 non-null  int64
 21  net_margin                       175149 non-null  float64
 22  num_years_antig                  175149 non-null  int64
 23  origin_up                        175149 non-null  object
 24  pow_max                          175149 non-null  float64
 25  contract_start_year              175149 non-null  int64
 26  price_off_peak_var_min           175149 non-null  float64
 27  price_off_peak_var_max           175149 non-null  float64
 28  price_peak_var_min               175149 non-null  float64
 29  price_peak_var_max               175149 non-null  float64
 30  price_mid_peak_var_min           175149 non-null  float64
 31  price_mid_peak_var_max           175149 non-null  float64
 32  price_off_peak_fix_min           175149 non-null  float64
 33  price_off_peak_fix_max           175149 non-null  float64
 34  price_peak_fix_min               175149 non-null  float64
 35  price_peak_fix_max               175149 non-null  float64
 36  price_mid_peak_fix_min           175149 non-null  float64
 37  price_mid_peak_fix_max           175149 non-null  float64
 38  price_off_peak_var_diff          175149 non-null  float64
 39  price_peak_var_diff              175149 non-null  float64
 40  price_mid_peak_var_diff          175149 non-null  float64
 41  price_off_peak_fix_diff          175149 non-null  float64
 42  price_peak_fix_diff              175149 non-null  float64
 43  price_mid_peak_fix_diff          175149 non-null  float64
 44  price_off_peak_var               175149 non-null  float64
 45  price_peak_var                   175149 non-null  float64
 46  price_mid_peak_var               175149 non-null  float64
 47  price_off_peak_fix               175149 non-null  float64
 48  price_peak_fix                   175149 non-null  float64
 49  price_mid_peak_fix               175149 non-null  float64
 50  churn                            175149 non-null  int64
 51  year_modif_prod                  175149 non-null  int64
 52  year_renewal                     175149 non-null  int64
 53  offpeak_diff_dec_january_energy  175149 non-null  float64
 54  offpeak_diff_dec_january_power   175149 non-null  float64
dtypes: datetime64[ns](4), float64(37), int64(10), object(4)
memory usage: 74.8+ MB

In [50]:
#drop unnecessary columns
cols_to_drop = ["id", 'date_activ','date_end','date_modif_prod','date_renewal']

In [69]:
train_df = eda_df.copy()
train_df = train_df.drop(columns=cols_to_drop)
train_df.head()

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix,churn,year_modif_prod,year_renewal,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,...,0.103395,0.071536,40.565969,24.339581,16.226389,1,2015,2015,0.020057,3.700961
1,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,...,0.103395,0.071536,40.565969,24.339581,16.226389,1,2015,2015,0.020057,3.700961
2,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,...,0.103395,0.071536,40.565973,24.339578,16.226383,1,2015,2015,0.020057,3.700961
3,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,...,0.103395,0.071536,40.565973,24.339578,16.226383,1,2015,2015,0.020057,3.700961
4,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,...,0.103395,0.071536,40.565973,24.339578,16.226383,1,2015,2015,0.020057,3.700961

### Transform columns

In [70]:
#one-hot encode categorical columns
cols_to_transform = ["channel_sales", "has_gas", "origin_up"]

In [71]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse=False)

ohe_df = pd.DataFrame(ohe.fit_transform(train_df[cols_to_transform])) 
ohe_df.columns = ohe.get_feature_names_out()
ohe_df.index = train_df.index
ohe_df.head()

,channel_sales_MISSING,channel_sales_epumfxlbckeskwekxbiuasklxalciiuu,channel_sales_ewpakwlliwisiwduibdlfmalxowmwpci,channel_sales_fixdbufsefwooaasfcxdxadsiekoceaa,channel_sales_foosdfpfkusacimwkcsosbicdxkicaua,channel_sales_lmkebamcaaclubfxadlmueccxoimlema,channel_sales_sddiedcslfslkckwlfkdpoeeailfpeds,channel_sales_usilxuppasemubllopkaafesmlibmsdf,has_gas_f,has_gas_t,origin_up_MISSING,origin_up_ewxeelcelemmiwuafmddpobolfuxioce,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,origin_up_ldkssxwpmemidmecebumciepifcamkci,origin_up_lxidpiddsbxsbosboudacockeimpuepw,origin_up_usapbepcfoloekilkwsdiboslwaxobdp
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [72]:
train_df = train_df.drop(cols_to_transform, axis=1)
train_df = pd.concat([train_df, ohe_df], axis=1)
train_df.head()

,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,forecast_price_pow_off_peak,...,channel_sales_sddiedcslfslkckwlfkdpoeeailfpeds,channel_sales_usilxuppasemubllopkaafesmlibmsdf,has_gas_f,has_gas_t,origin_up_MISSING,origin_up_ewxeelcelemmiwuafmddpobolfuxioce,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,origin_up_ldkssxwpmemidmecebumciepifcamkci,origin_up_lxidpiddsbxsbosboudacockeimpuepw,origin_up_usapbepcfoloekilkwsdiboslwaxobdp
0,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,40.606701,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,40.606701,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,40.606701,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,40.606701,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0,54946,0,0.0,0,0.0,1.78,0.114481,0.098142,40.606701,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

## 3. Save Data

In [77]:
with open(FE_DATA_EXPORT_PATH, "wb") as file:
    pickle.dump(train_df, file)